import { v4 as uuidv4 } from "uuid";
import ProductImage1 from "./assets/Search/ProductImage1.png";
import ProductImage2 from "./assets/Search/ProductImage2.png";
import ProductImage3 from "./assets/Search/ProductImage3.png";
import ProductImage4 from "./assets/Search/ProductImage4.png";
import ProductImage5 from "./assets/Search/ProductImage5.png";
import ProductImage6 from "./assets/Search/ProductImage6.png";
import ShopAllProductImage1 from "./assets/ShopAll/ShopAllProductImage1.png";
import ShopAllProductImage2 from "./assets/ShopAll/ShopAllProductImage2.png";
import ShopAllProductImage3 from "./assets/ShopAll/ShopAllProductImage3.png";
import ShopAllProductImage4 from "./assets/ShopAll/ShopAllProductImage4.png";
import ShopAllProductImage5 from "./assets/ShopAll/ShopAllProductImage5.png";
import ShopAllProductImage6 from "./assets/ShopAll/ShopAllProductImage6.png";
import BestSellers1 from "./assets/BestSellers/ProductImage1.png";
import BestSellers2 from "./assets/BestSellers/ProductImage2.png";
import BestSellers3 from "./assets/BestSellers/ProductImage3.png";
import { Product } from "./types";

export const filterList = [
	{
		id: uuidv4(),
		title: "Sort By",
		list: [
			{ id: uuidv4(), label: "Featured" },
			{ id: uuidv4(), label: "Best Seller" },
			{ id: uuidv4(), label: "Price: Low To High" },
			{ id: uuidv4(), label: "Price: High To Low" },
		],
	},
	{
		id: uuidv4(),
		title: "Size",
		list: [
			{ id: uuidv4(), label: "XS / US (0-4)" },
			{ id: uuidv4(), label: "S / US (4-6)" },
			{ id: uuidv4(), label: "M / US (6-10)" },
			{ id: uuidv4(), label: "L / US (10-14)" },
			{ id: uuidv4(), label: "XL / US (12-16)" },
		],
	},
	{
		id: uuidv4(),
		title: "Color",
		list: [
			{ id: uuidv4(), label: "Black", className: "bg-[#000000]" },
			{ id: uuidv4(), label: "Red", className: "bg-[#FF0000]" },
			{ id: uuidv4(), label: "Green", className: "bg-[#00FF00]" },
			{ id: uuidv4(), label: "Yellow", className: "bg-[#FFFF00]" },
			{ id: uuidv4(), label: "Dark Blue", className: "bg-[#00008B]" },
			{ id: uuidv4(), label: "Purple", className: "bg-[#800080]" },
			{ id: uuidv4(), label: "Pink", className: "bg-[#FFC0CB]" },
			{ id: uuidv4(), label: "Light Blue", className: "bg-[#ADD8E6]" },
			{ id: uuidv4(), label: "Orange", className: "bg-[#FFA500]" },
			{ id: uuidv4(), label: "White", className: "bg-[#FFFFFF]" },
		],
	},
	{
		id: uuidv4(),
		title: "Collection",
		list: [
			{ id: uuidv4(), label: "In Stock" },
			{ id: uuidv4(), label: "Out Of Stock" },
		],
	},
	{
		id: uuidv4(),
		title: "Fabric",
		list: [
			{ id: uuidv4(), label: "Cotton" },
			{ id: uuidv4(), label: "Linen" },
			{ id: uuidv4(), label: "Wool" },
			{ id: uuidv4(), label: "Silk" },
			{ id: uuidv4(), label: "Cashmere" },
		],
	},
];

export const allProducts: Product[] = [
	{
		id: "3efa71cb-24ab-4fd5-a40c-8960bed3d87c",
		name: "Elastic Waist",
		description: "Turn it Up Pants",
		images: [ProductImage1, ProductImage2, ProductImage3, ProductImage4, ProductImage5],
		price: 110,
		colors: [
			{ id: uuidv4(), label: "Dark Blue", className: "bg-[#7DC3EB]" },
			{ id: uuidv4(), label: "Sage", className: "bg-[#748C70]" },
		],
		keywords: [
			"elastic waist",
			"turn it up",
			"pants",
			"casual pants",
			"comfortable",
			"relaxed fit",
		],
		sizes: [
			{ value: "XS", label: "XS / US (0-4)" },
			{ value: "S", label: "S / US (4-6)" },
			{ value: "M", label: "M / US (6-10)" },
			{ value: "L", label: "L / US (10-14)" },
			{ value: "XL", label: "XL / US (12-16)" },
		],

		fabric: "Cotton",
	},
	{
		id: "e580fee8-648d-47c3-b5fa-00f29b98c75d",
		name: "Tailored Stretch",
		description: "Make A Splash",
		images: [ProductImage2, ProductImage3, ProductImage4, ProductImage5, ProductImage6],
		price: 150,
		colors: [{ id: uuidv4(), label: "Black", className: "bg-black" }],
		keywords: ["tailored pants", "stretch pants", "fitted pants", "black pants", "formal pants"],
		sizes: [
			{ value: "XS", label: "XS / US (0-4)" },
			{ value: "S", label: "S / US (4-6)" },
			{ value: "M", label: "M / US (6-10)" },
			{ value: "L", label: "L / US (10-14)" },
			{ value: "XL", label: "XL / US (12-16)" },
		],
		fabric: "Cotton",
	},
	{
		id: "30bfc28c-66ae-4ba1-a1ce-411cb4d1a6fd",
		name: "Tailored Stretch",
		description: "Turn It Up Pants",
		images: [ProductImage3, ProductImage4, ProductImage5, ProductImage6, ProductImage1],
		price: 140,
		colors: [
			{ id: uuidv4(), label: "Black", className: "bg-[#0C0C0C]" },
			{ id: uuidv4(), label: "Red", className: "bg-[#CA2929]" },
			{ id: uuidv4(), label: "Sage", className: "bg-[#748C70]" },
		],
		keywords: [
			"tailored",
			"stretch pants",
			"fitted trousers",
			"turn it up",
			"black pants",
			"crimson pants",
		],
		sizes: [
			{ value: "XS", label: "XS / US (0-4)" },
			{ value: "S", label: "S / US (4-6)" },
			{ value: "M", label: "M / US (6-10)" },
			{ value: "L", label: "L / US (10-14)" },
			{ value: "XL", label: "XL / US (12-16)" },
		],
		fabric: "Cashmere",
	},
	{
		id: "e9a710a2-1944-4556-9a04-9c0219d9a5f3",
		name: "High Tillie",
		description: "Turn It Up Pants",
		images: [ProductImage4, ProductImage5, ProductImage6, ProductImage1, ProductImage2],
		price: 110,
		colors: [
			{ id: uuidv4(), label: "Black", className: "bg-[#0C0C0C]" },
			{ id: uuidv4(), label: "Green", className: "bg-[#909225]" },
			{ id: uuidv4(), label: "Sage", className: "bg-[#748C70]" },
		],
		keywords: [
			"high waist",
			"tillie pants",
			"turn it up",
			"elevated fit",
			"olive pants",
			"black trousers",
		],
		sizes: [
			{ value: "XS", label: "XS / US (0-4)" },
			{ value: "S", label: "S / US (4-6)" },
			{ value: "M", label: "M / US (6-10)" },
			{ value: "L", label: "L / US (10-14)" },
			{ value: "XL", label: "XL / US (12-16)" },
		],
		fabric: "Silk",
	},
	{
		id: "8ae87533-faaf-481b-966c-9a50539748df",
		name: "Casual Wild Leg",
		description: "Turn It Up Pants",
		images: [
			ProductImage5,
			ProductImage6,
			ProductImage1,
			ProductImage2,
			ProductImage3,
			ProductImage4,
		],
		price: 130,
		colors: [
			{ id: uuidv4(), label: "Black", className: "bg-[#0C0C0C]" },
			{ id: uuidv4(), label: "Sage", className: "bg-[#748C70]" },
		],
		categories: ["Featured"],
		keywords: ["casual pants", "wide leg", "wild leg", "turn it up", "black pants", "sage pants"],
		sizes: [
			{ value: "XS", label: "XS / US (0-4)" },
			{ value: "S", label: "S / US (4-6)" },
			{ value: "M", label: "M / US (6-10)" },
			{ value: "L", label: "L / US (10-14)" },
			{ value: "XL", label: "XL / US (12-16)" },
		],
		fabric: "Wool",
	},
	{
		id: "fa29542c-848b-4ac7-b8f5-12d2352401ed",
		name: "Linen Wide Leg",
		description: "Turn It Up Pants",
		images: [ProductImage6, ProductImage1, ProductImage3, ProductImage4, ProductImage5],
		price: 180,
		colors: [
			{ id: uuidv4(), label: "Black", className: "bg-[#0C0C0C]" },
			{ id: uuidv4(), label: "Lavender", className: "bg-[#D0A5EA]" },
		],
		keywords: [
			"linen pants",
			"wide leg",
			"breathable",
			"lavender pants",
			"relaxed fit",
			"summer pants",
		],
		sizes: [
			{ value: "XS", label: "XS / US (0-4)" },
			{ value: "S", label: "S / US (4-6)" },
			{ value: "M", label: "M / US (6-10)" },
			{ value: "L", label: "L / US (10-14)" },
			{ value: "XL", label: "XL / US (12-16)" },
		],
		fabric: "Linen",
	},
	{
		id: "55a221c7-cc46-47c3-8453-554140dd9805",
		name: "Tailored Stretch",
		description: "Turn it Up Pants",
		images: [BestSellers1, BestSellers2, BestSellers3],
		price: 180,
		colors: [
			{ id: uuidv4(), label: "Dark Grey", className: "bg-[#0C0C0C]" },
			{ id: uuidv4(), label: "Dark Blue", className: "bg-[#7DC3EB]" },
			{ id: uuidv4(), label: "Sage", className: "bg-[#748C70]" },
		],
		categories: ["Best Seller"],
		keywords: [
			"tailored",
			"stretch",
			"turn it up",
			"best seller",
			"sky blue",
			"sage pants",
			"dark grey pants",
		],
		sizes: [
			{ value: "XS", label: "XS / US (0-4)" },
			{ value: "S", label: "S / US (4-6)" },
			{ value: "M", label: "M / US (6-10)" },
			{ value: "L", label: "L / US (10-14)" },
			{ value: "XL", label: "XL / US (12-16)" },
		],
		fabric: "Wool",
	},
	{
		id: "c68975d5-0b9c-4dc4-8a06-a5af2cc9f4d9",
		name: "Technical Silk",
		description: "Make A Splash",
		images: [BestSellers2],

		price: 120,
		colors: [
			{ id: uuidv4(), label: "Green", className: "bg-[#909225]" },
			{ id: uuidv4(), label: "Navy", className: "bg-[#19418E]" },
		],
		categories: ["Best Seller"],
		keywords: ["technical silk", "silky pants", "olive", "navy", "smooth fabric", "splash"],
		sizes: [
			{ value: "XS", label: "XS / US (0-4)" },
			{ value: "S", label: "S / US (4-6)" },
			{ value: "M", label: "M / US (6-10)" },
			{ value: "L", label: "L / US (10-14)" },
			{ value: "XL", label: "XL / US (12-16)" },
		],
		fabric: "Linen",
	},
	{
		id: "0c247359-e970-4fff-89dd-ed93b47dfec6",
		name: "Cool Weave",
		description: "Anywhere Dress",
		images: [BestSellers3, BestSellers1, BestSellers1],
		price: 210,
		colors: [
			{ id: uuidv4(), label: "Lavender", className: "bg-[#D0A5EA]" },
			{ id: uuidv4(), label: "Black", className: "bg-[#0C0C0C]" },
			{ id: uuidv4(), label: "Yellow", className: "bg-[#748C70]" },
		],
		tag: "",
		categories: ["Best Seller"],
		keywords: [
			"cool weave",
			"dress",
			"anywhere dress",
			"lavender dress",
			"sage",
			"breathable",
			"elegant dress",
		],
		sizes: [
			{ value: "XS", label: "XS / US (0-4)" },
			{ value: "S", label: "S / US (4-6)" },
			{ value: "M", label: "M / US (6-10)" },
			{ value: "L", label: "L / US (10-14)" },
			{ value: "XL", label: "XL / US (12-16)" },
		],

		fabric: "Cashmere",
	},
	{
		id: "c605510e-8bfd-41b7-97af-282f0a15e426",
		name: "Chill Wrap Top",
		description: "Turn it Up Top",
		images: [ShopAllProductImage1],
		price: 160,
		colors: [{ id: uuidv4(), label: "Green", className: "bg-[#909225]" }],
		tag: "New",
		categories: ["shopAll"],
		keywords: ["wrap top", "chill top", "turn it up", "olive", "casual top", "new arrival"],
		sizes: [
			{ value: "XS", label: "XS / US (0-4)" },
			{ value: "S", label: "S / US (4-6)" },
			{ value: "M", label: "M / US (6-10)" },
			{ value: "L", label: "L / US (10-14)" },
			{ value: "XL", label: "XL / US (12-16)" },
		],
		fabric: "Cotton",
	},
	{
		id: "bec640cd-7cb4-4d7b-88cd-fccedb661169",
		name: "Essential T-shirt",
		description: "Turn it Up T-Shirt",
		images: [ShopAllProductImage2],
		price: 95,

		colors: [
			{ id: uuidv4(), label: "Black", className: "bg-[#0C0C0C]" },
			{ id: uuidv4(), label: "Light Blue", className: "bg-[#7DC3EB]" },
			{ id: uuidv4(), label: "Sage", className: "bg-[#748C70]" },
		],
		tag: "",
		categories: ["shopAll"],
		keywords: ["essential", "t-shirt", "turn it up", "black t-shirt", "sky blue", "casual wear"],
		sizes: [
			{ value: "XS", label: "XS / US (0-4)" },
			{ value: "S", label: "S / US (4-6)" },
			{ value: "M", label: "M / US (6-10)" },
			{ value: "L", label: "L / US (10-14)" },
			{ value: "XL", label: "XL / US (12-16)" },
		],
		fabric: "Linen",
	},
	{
		id: "cdd2169d-25c8-4ef2-8b5f-fdce7bb7976e",
		name: "Shirt Dress",
		description: "Turn It Up Dress",
		images: [ShopAllProductImage3],
		price: 245,
		colors: [
			{ id: uuidv4(), label: "Black", className: "bg-[#0C0C0C]" },
			{ id: uuidv4(), label: "Sky Blue", className: "bg-[#7DC3EB]" },
			{ id: uuidv4(), label: "Sage", className: "bg-[#748C70]" },
		],
		tag: "New",
		categories: ["shopAll"],
		keywords: [
			"shirt dress",
			"turn it up",
			"new arrival",
			"sky blue dress",
			"elevated casual",
			"day dress",
		],
		sizes: [
			{ value: "XS", label: "XS / US (0-4)" },
			{ value: "S", label: "S / US (4-6)" },
			{ value: "M", label: "M / US (6-10)" },
			{ value: "L", label: "L / US (10-14)" },
			{ value: "XL", label: "XL / US (12-16)" },
		],
		fabric: "Wool",
	},
	{
		id: "88d82e1f-d4eb-446e-af86-c34691b683af",
		name: "Rule Zip Jacket",
		description: "Turn It Up Jacket",
		images: [ShopAllProductImage4],
		price: 199,
		colors: [
			{ id: uuidv4(), label: "Olive", className: "bg-[#909225]" },
			{ id: uuidv4(), label: "Orange", className: "bg-[#CA6D29]" },
		],
		tag: "",
		categories: ["shopAll"],
		keywords: [
			"rule jacket",
			"zip jacket",
			"turn it up",
			"burnt orange",
			"olive jacket",
			"outerwear",
		],
		sizes: [
			{ value: "XS", label: "XS / US (0-4)" },
			{ value: "S", label: "S / US (4-6)" },
			{ value: "M", label: "M / US (6-10)" },
			{ value: "L", label: "L / US (10-14)" },
			{ value: "XL", label: "XL / US (12-16)" },
		],
		fabric: "Cotton",
	},
	{
		id: "6c882520-c71b-44bb-8759-30a27554d2c5",
		name: "New Age Linen",
		description: "Turn It Up Pants",
		images: [ShopAllProductImage5],
		price: 180,
		colors: [
			{ id: uuidv4(), label: "Black", className: "bg-[#0C0C0C]" },
			{ id: uuidv4(), label: "Navy", className: "bg-[#19418E]" },
			{ id: uuidv4(), label: "Sage", className: "bg-[#748C70]" },
		],
		tag: "",
		categories: ["shopAll"],
		keywords: [
			"new age",
			"linen pants",
			"black pants",
			"navy",
			"sage",
			"breathable",
			"modern trousers",
		],
		sizes: [
			{ value: "XS", label: "XS / US (0-4)" },
			{ value: "S", label: "S / US (4-6)" },
			{ value: "M", label: "M / US (6-10)" },
			{ value: "L", label: "L / US (10-14)" },
			{ value: "XL", label: "XL / US (12-16)" },
		],
		fabric: "Cashmere",
	},
	{
		id: "12ac6bc4-b61b-458a-b874-3cff9f02f4e7",
		name: "Boss Pullover",
		description: "Turn It Up Pullover",
		images: [ShopAllProductImage6],
		price: 280,
		tag: "New",
		colors: [
			{ id: uuidv4(), label: "Black", className: "bg-[#0C0C0C]" },
			{ id: uuidv4(), label: "Sage", className: "bg-[#748C70]" },
		],
		categories: ["shopAll"],
		keywords: [
			"boss pullover",
			"turn it up",
			"new",
			"sage",
			"black pullover",
			"sweater",
			"comfortable",
		],
		sizes: [
			{ value: "XS", label: "XS / US (0-4)" },
			{ value: "S", label: "S / US (4-6)" },
			{ value: "M", label: "M / US (6-10)" },
			{ value: "L", label: "L / US (10-14)" },
			{ value: "XL", label: "XL / US (12-16)" },
		],
		fabric: "Cotton",
	},
];
